"use client";

import { useMemo, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

const base = "http://localhost:3000";
const source = [
"# Object Storage API",
"",
"Upload, organize, stream, and serve files through a bucket-isolated Google Drive storage API.",
"",
"## Authentication",
"",
"Semua request API memakai API key pada header berikut:",
"",
"~~~http",
"Authorization: Bearer $API_KEY",
"~~~",
"",
"## Quickstart",
"",
"~~~bash",
`curl -X POST ${base}/api/v1/objects \\\n  -H "Authorization: Bearer $API_KEY" \\\n  -F "file=@./video.mp4" \\\n  -F "path=/videos/2026/episode-01.mp4"`,
"~~~",
"",
"Path nested otomatis membuat folder yang belum ada di database dan Google Drive.",
"",
"## Buckets",
"",
"| Method | Endpoint | Keterangan |",
"| --- | --- | --- |",
"| GET | /api/v1/buckets | List bucket milik user |",
"| POST | /api/v1/buckets | Buat bucket baru |",
"| GET | /api/v1/buckets/:id | Detail bucket |",
"| PUT | /api/v1/buckets/:id | Update bucket |",
"| DELETE | /api/v1/buckets/:id | Hapus jika kosong |",
"| GET | /api/v1/buckets/:id/usage | Usage logical bucket |",
"",
"~~~json",
'{\n  "name": "video-production",\n  "slug": "video-production",\n  "max_bytes": 107374182400\n}',
"~~~",
"",
"## API Keys",
"",
"| Method | Endpoint | Keterangan |",
"| --- | --- | --- |",
"| GET | /api/v1/api-keys | List API key |",
"| POST | /api/v1/api-keys | Generate key baru |",
"| GET | /api/v1/api-keys/:id | Detail tanpa raw key |",
"| PUT | /api/v1/api-keys/:id | Update name, permission, status |",
"| DELETE | /api/v1/api-keys/:id | Revoke key |",
"| POST | /api/v1/api-keys/:id/rotate | Rotate key |",
"",
"Raw key hanya muncul sekali saat create atau rotate. Setiap key terikat ke tepat satu bucket.",
"",
"## Folders",
"",
"| Method | Endpoint | Keterangan |",
"| --- | --- | --- |",
"| GET | /api/v1/folders?parent_id=:id | List child folder |",
"| POST | /api/v1/folders | Buat folder |",
"| GET | /api/v1/folders/:id | Detail folder |",
"| PUT | /api/v1/folders/:id | Rename atau pindah folder |",
"| DELETE | /api/v1/folders/:id | Hapus recursive sampai Google Drive |",
"",
"## Objects",
"",
"| Method | Endpoint | Keterangan |",
"| --- | --- | --- |",
"| POST | /api/v1/objects | Upload file atau video |",
"| GET | /api/v1/objects | List object |",
"| GET | /api/v1/objects/:id | Metadata object |",
"| GET | /api/v1/objects/:id/download | Download / HTTP Range 206 |",
"| PUT | /api/v1/objects/:id | Update nama atau folder |",
"| POST | /api/v1/objects/:id/move | Move object |",
"| DELETE | /api/v1/objects/:id | Hapus object fisik dan metadata |",
"",
"~~~bash",
`curl -X POST ${base}/api/v1/objects \\\n  -H "Authorization: Bearer $API_KEY" \\\n  -F "file=@./episode.mp4" \\\n  -F "path=/series/season-01/episode-01.mp4"`,
"~~~",
"",
"## Public URLs",
"",
"| Method | Endpoint | Keterangan |",
"| --- | --- | --- |",
"| POST | /api/v1/objects/:id/public-url | Generate URL dengan expiry |",
"| GET | /public/:token/:filename | Akses public object dan stream |",
"| DELETE | /api/v1/objects/:id/public-url | Revoke URL |",
"",
"~~~json",
'{\n  "expires_in": 3600\n}',
"~~~",
"",
"## Custom Domains",
"",
"| Method | Endpoint | Keterangan |",
"| --- | --- | --- |",
"| GET | /api/v1/domains | List domain |",
"| POST | /api/v1/domains | Add domain |",
"| DELETE | /api/v1/domains/:id | Remove domain |",
"| POST | /api/v1/domains/:id/verify | Mark verified |",
"",
"## Errors",
"",
"~~~json",
'{\n  "success": false,\n  "error": {\n    "code": "PERMISSION_DENIED",\n    "message": "API key does not have file:create permission"\n  }\n}',
"~~~",
"",
"Common codes: UNAUTHORIZED, PERMISSION_DENIED, NOT_FOUND, BUCKET_NOT_EMPTY, INSUFFICIENT_STORAGE, STORAGE_ERROR."
].join("\n");

const sections = ["Authentication", "Quickstart", "Buckets", "API Keys", "Folders", "Objects", "Public URLs", "Custom Domains", "Errors"];

export function StorageApiDocs() {
  const [copied, setCopied] = useState("");
  const markdown = useMemo(() => source, []);
  const copy = async (value: string) => { await navigator.clipboard.writeText(value); setCopied(value); setTimeout(() => setCopied(""), 1200); };
  return <div className="liquid-universe"><div className="ambient-blob blob-one" /><div className="ambient-blob blob-two" /><div className="ambient-blob blob-three" /><div className="glass-container-full"><main className="storage-docs-page"><header className="storage-docs-hero"><span className="eyebrow">ALLDRIVE DEVELOPER DOCS</span><h1>Object Storage API</h1><p>Dokumentasi API bucket, nested storage, streaming, dan public URL.</p><div className="docs-hero-actions"><a className="btn accent" href="/dashboard/storage">Open Storage</a><a className="btn ghost" href="/dashboard/api-keys">Manage API Keys</a></div></header><div className="docs-layout"><aside className="docs-sidebar"><strong>On this page</strong>{sections.map((section) => <a key={section} href={`#${section.toLowerCase().replaceAll(" ", "-")}`}>{section}</a>)}</aside><article className="docs-markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{ h2: ({ children, ...props }) => <h2 id={String(children).toLowerCase().replaceAll(" ", "-")} {...props}>{children}</h2>, pre: ({ children }) => <div className="docs-code"><button onClick={() => { const code = String((children as any)?.props?.children || ""); void copy(code); }}>{copied ? "Copied" : "Copy"}</button><pre>{children}</pre></div> }}>{markdown}</ReactMarkdown></article></div></main></div></div>;
}
